print("yes")
print("yes yes")
print("no")
print("no no")
print("no no no")
print("This is the git command")
print("This is the git command 2")
print("This is vs command")
print("This is vs command 2")